// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PhoneNumber struct {
	ID          int32  `db:"id" json:"id"`
	UserID      int32  `db:"user_id" json:"user_id"`
	PhoneNumber string `db:"phone_number" json:"phone_number"`
}

type Sm struct {
	ID            int32            `db:"id" json:"id"`
	UserID        int32            `db:"user_id" json:"user_id"`
	PhoneNumberID int32            `db:"phone_number_id" json:"phone_number_id"`
	ToPhoneNumber string           `db:"to_phone_number" json:"to_phone_number"`
	Message       string           `db:"message" json:"message"`
	Status        string           `db:"status" json:"status"`
	DeliveredAt   pgtype.Timestamp `db:"delivered_at" json:"delivered_at"`
}

type User struct {
	ID       int32          `db:"id" json:"id"`
	Username string         `binding:"required,alphanum" db:"username" json:"username"`
	Balance  pgtype.Numeric `db:"balance" json:"balance"`
}
