# https://taskfile.dev
version: "3"

vars:
  POSTGRES_USER: root

includes:
  charts:
    taskfile: ./charts/Taskfile.yml
    dir: ./charts
tasks:
  build:
    cmds:
      - go build -o bin/sms .
  run:
    deps: [sqlc:gen]
    cmds:
      - go run . api
  run:worker:
    deps: [sqlc:gen]
    cmds:
      - go run . worker
  mk:start:
    cmds:
      - minikube start
  mk:init:
    cmds:
      - minikube start --nodes 3 --listen-address 0.0.0.0
  kc:pf:nats:
    cmds:
      - kubectl port-forward pod/nats-0 4222:4222 &
  kc:pf:postgres:
    cmds:
      - kubectl port-forward deployment/postgres 5433:5432 &
  db:init:
    cmds:
      - psql -U {{.POSTGRES_USER}} -h localhost -f ./schema.sql
  db:clear:
    cmds:
      - psql -U {{.POSTGRES_USER}} -h localhost -c 'DROP SCHEMA public CASCADE'
  sqlc:gen:
    cmds:
      - sqlc generate
  docker:build:
    cmds:
      - go build -o ./bin/sms .
      - docker buildx build -t reffined/sms:v1 .
