# https://taskfile.dev
version: "3"

includes:
  proto:
    taskfile: ./proto/Taskfile.yml
    dir: ./proto
  charts:
    taskfile: ./charts/Taskfile.yml
    dir: ./charts

tasks:
  build:
    deps: [proto:build]
    cmds:
      - go build -o bin/sms .
  run:
    deps: [proto:build]
    cmds:
      - go run .
