# https://taskfile.dev
version: "3"

vars:
  POSTGRES_USER: root

includes:
  proto:
    taskfile: ./proto/Taskfile.yml
    dir: ./proto
  charts:
    taskfile: ./charts/Taskfile.yml
    dir: ./charts
tasks:
  build:
    deps: [proto:build]
    cmds:
      - go build -o bin/sms .
  run:
    deps: [proto:build]
    cmds:
      - task: kc:pf:nats
      - task: kc:pf:postgres
      - defer: pkill kubectl
      - go run . api
  run:worker:
    deps: [proto:build]
    cmds:
      - task: kc:pf:nats
      - defer: pkill kubectl
      - go run . worker
  mk:start:
    cmds:
      - minikube start
  mk:init:
    cmds:
      - minikube start --nodes 3 --listen-address 0.0.0.0
  kc:pf:nats:
    cmds:
      - kubectl port-forward pod/nats-0 4222:4222 &
  kc:pf:postgres:
    cmds:
      - kubectl port-forward deployment/postgres 5433:5432 &
  db:migrate:
    sources: [./migrations/*.sql]
    generates: [mock]
    cmds:
      - for: sources
        cmd: psql -U {{.POSTGRES_USER}} -h localhost -f {{.ITEM}}
