# https://taskfile.dev
version: "3"

includes:
  proto:
    taskfile: ./proto/Taskfile.yml
    dir: ./proto
  charts:
    taskfile: ./charts/Taskfile.yml
    dir: ./charts

tasks:
  build:
    deps: [proto:build]
    cmds:
      - go build -o bin/sms .
  run:
    deps: [proto:build]
    cmds:
      - task: kc:pf:nats
      - defer: pkill kubectl
      - go run . api -l "127.0.0.1:8080"
  mk:start:
    cmds:
      - minikube start
  mk:init:
    cmds:
      - minikube start --nodes 3 --listen-address 0.0.0.0
  kc:pf:nats:
    cmds:
      - printf "nats service at %s\n" {{.ADD}}
      - kubectl port-forward pod/nats-0 4222:4222 &
