// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryStatus int32

const (
	DeliveryStatus_pending   DeliveryStatus = 0
	DeliveryStatus_failed    DeliveryStatus = 1
	DeliveryStatus_delivered DeliveryStatus = 2
)

// Enum value maps for DeliveryStatus.
var (
	DeliveryStatus_name = map[int32]string{
		0: "pending",
		1: "failed",
		2: "delivered",
	}
	DeliveryStatus_value = map[string]int32{
		"pending":   0,
		"failed":    1,
		"delivered": 2,
	}
)

func (x DeliveryStatus) Enum() *DeliveryStatus {
	p := new(DeliveryStatus)
	*p = x
	return p
}

func (x DeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[0].Descriptor()
}

func (DeliveryStatus) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[0]
}

func (x DeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryStatus.Descriptor instead.
func (DeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

type SmsPriority int32

const (
	SmsPriority_normal SmsPriority = 0
	SmsPriority_high   SmsPriority = 1
)

// Enum value maps for SmsPriority.
var (
	SmsPriority_name = map[int32]string{
		0: "normal",
		1: "high",
	}
	SmsPriority_value = map[string]int32{
		"normal": 0,
		"high":   1,
	}
)

func (x SmsPriority) Enum() *SmsPriority {
	p := new(SmsPriority)
	*p = x
	return p
}

func (x SmsPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmsPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_enumTypes[1].Descriptor()
}

func (SmsPriority) Type() protoreflect.EnumType {
	return &file_api_proto_enumTypes[1]
}

func (x SmsPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SmsPriority.Descriptor instead.
func (SmsPriority) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username      *string                `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Balance       *uint64                `protobuf:"varint,3,opt,name=balance" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *User) GetBalance() uint64 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

type Sms struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserId        *uint64                `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	PhoneNumberId *uint64                `protobuf:"varint,3,opt,name=phone_number_id,json=phoneNumberId" json:"phone_number_id,omitempty"`
	Msg           *string                `protobuf:"bytes,4,opt,name=msg" json:"msg,omitempty"`
	Status        *DeliveryStatus        `protobuf:"varint,5,opt,name=status,enum=api.DeliveryStatus" json:"status,omitempty"`
	DeliveredAt   *uint64                `protobuf:"varint,6,opt,name=delivered_at,json=deliveredAt" json:"delivered_at,omitempty"`
	Priority      *SmsPriority           `protobuf:"varint,7,opt,name=priority,enum=api.SmsPriority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sms) Reset() {
	*x = Sms{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sms) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sms) ProtoMessage() {}

func (x *Sms) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sms.ProtoReflect.Descriptor instead.
func (*Sms) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *Sms) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Sms) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *Sms) GetPhoneNumberId() uint64 {
	if x != nil && x.PhoneNumberId != nil {
		return *x.PhoneNumberId
	}
	return 0
}

func (x *Sms) GetMsg() string {
	if x != nil && x.Msg != nil {
		return *x.Msg
	}
	return ""
}

func (x *Sms) GetStatus() DeliveryStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return DeliveryStatus_pending
}

func (x *Sms) GetDeliveredAt() uint64 {
	if x != nil && x.DeliveredAt != nil {
		return *x.DeliveredAt
	}
	return 0
}

func (x *Sms) GetPriority() SmsPriority {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return SmsPriority_normal
}

type PhoneNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	UserId        *uint64                `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Number        *string                `protobuf:"bytes,3,opt,name=number" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneNumber) Reset() {
	*x = PhoneNumber{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneNumber) ProtoMessage() {}

func (x *PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneNumber.ProtoReflect.Descriptor instead.
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *PhoneNumber) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PhoneNumber) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *PhoneNumber) GetNumber() string {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return ""
}

type AddPhoneNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	PhoneNumber   *string                `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPhoneNumberRequest) Reset() {
	*x = AddPhoneNumberRequest{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPhoneNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPhoneNumberRequest) ProtoMessage() {}

func (x *AddPhoneNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPhoneNumberRequest.ProtoReflect.Descriptor instead.
func (*AddPhoneNumberRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *AddPhoneNumberRequest) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *AddPhoneNumberRequest) GetPhoneNumber() string {
	if x != nil && x.PhoneNumber != nil {
		return *x.PhoneNumber
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x03api\"L\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x04R\abalance\"\xe6\x01\n" +
	"\x03Sms\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12&\n" +
	"\x0fphone_number_id\x18\x03 \x01(\x04R\rphoneNumberId\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.api.DeliveryStatusR\x06status\x12!\n" +
	"\fdelivered_at\x18\x06 \x01(\x04R\vdeliveredAt\x12,\n" +
	"\bpriority\x18\a \x01(\x0e2\x10.api.SmsPriorityR\bpriority\"N\n" +
	"\vPhoneNumber\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\"V\n" +
	"\x15AddPhoneNumberRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber*8\n" +
	"\x0eDeliveryStatus\x12\v\n" +
	"\apending\x10\x00\x12\n" +
	"\n" +
	"\x06failed\x10\x01\x12\r\n" +
	"\tdelivered\x10\x02*#\n" +
	"\vSmsPriority\x12\n" +
	"\n" +
	"\x06normal\x10\x00\x12\b\n" +
	"\x04high\x10\x01B\vZ\tproto/apib\beditionsp\xe8\a"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_goTypes = []any{
	(DeliveryStatus)(0),           // 0: api.DeliveryStatus
	(SmsPriority)(0),              // 1: api.SmsPriority
	(*User)(nil),                  // 2: api.User
	(*Sms)(nil),                   // 3: api.Sms
	(*PhoneNumber)(nil),           // 4: api.PhoneNumber
	(*AddPhoneNumberRequest)(nil), // 5: api.AddPhoneNumberRequest
}
var file_api_proto_depIdxs = []int32{
	0, // 0: api.Sms.status:type_name -> api.DeliveryStatus
	1, // 1: api.Sms.priority:type_name -> api.SmsPriority
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		EnumInfos:         file_api_proto_enumTypes,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
