# https://taskfile.dev
version: "3"

vars:
  ADDRESS: http://localhost:8080

tasks:
  user:create:
    vars:
      NEW_USER:
        sh: cat ./new_user.json
    cmds:
      - curl -X POST -L --stderr /dev/null --json '{{.NEW_USER}}' {{.ADDRESS}}/user | jq
  user:addBalance:
    cmds:
      - curl -X PUT -L --stderr /dev/null --json '
        {
        "username":"{{.USERNAME}}",
        "balance":{{.BALANCE}}
        }' {{.ADDRESS}}/user/balance | jq

  phone:create:
    vars:
      USER_ID:
        sh: curl -X GET -L --stderr /dev/null {{.ADDRESS}}/user/{{.USERNAME}} | jq '.id'
      NEW_PHONE:
        sh: cat ./new_phone.json | jq --argjson id {{.USER_ID}} '.user_id = $id'
    cmds:
      - curl -X POST -L --stderr /dev/null --json '{{.NEW_PHONE}}' {{.ADDRESS}}/phone-number |jq

  phone:get:
    cmds:
      - curl -X GET -L --stderr /dev/null {{.ADDRESS}}/phone-number/{{.PHONE_ID}} | jq

  phone:delete:
    cmds:
      - curl -X DELETE -L --stderr /dev/null {{.ADDRESS}}/phone-number/{{.PHONE_ID}} | jq

  phone:getByUser:
    cmds:
      - curl -X GET -L --stderr /dev/null {{.ADDRESS}}/phone-number/user/{{.USERNAME}} | jq
