# https://taskfile.dev
version: "3"

vars:
  ADDRESS: http://localhost:8080
  NEW_USER:
    sh: cat ./new_user.json

tasks:
  create:user:
    cmds:
      - curl -X POST -L --json '{{.NEW_USER}}' {{.ADDRESS}}/user
